apiVersion: v1
kind: Pod
metadata:
  name: asker
spec:
  containers:
  - name: server
    image: asker
    ports:
    - containerPort: 50051
    env:
    - name: PORT
      value: "50051"
    - name: GREETER_SERVICE_ADDR
      value: "greeterservice:50051"
  initContainers:
    - name: wait
      image: busybox:1.28
      command: ['sh', '-c', 'sleep 10']